steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'us-east5-docker.pkg.dev/pricecharts/price-charts/price_charts:0.2',
           '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'us-east5-docker.pkg.dev/pricecharts/price-charts/price_charts:0.2']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    timeout: 240s
    args: ['compute', 'instances',
           'create-with-container', 'my-vm-name',
           '--container-image',
           'us-east5-docker.pkg.dev/pricecharts/price-charts/price_charts:0.2']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-east5'
      - 'CLOUDSDK_COMPUTE_ZONE=us-east5-a'

options:
  logging: NONE
