spring:
  application:
    name: price_charts
  thymeleaf:
    cache: false

server:
  address: 0.0.0.0
  port: 8080

polygon:
  api:
    key: uA0b68posq6OqaQCGHs_5fvpBB0P7z8w #this make app independent in tests
