spring:
  application:
    name: bitcoin_charts
  thymeleaf:
    cache: false

server:
  address: 0.0.0.0
  port: 8080

binance:
  api:
    key: -1 #come through launch parameters
    secret: -1 #come through launch parameters
