apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-charts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-charts
  template:
    metadata:
      labels:
        app: price-charts
    spec:
      containers:
        - name: price-charts
          image: us-east5-docker.pkg.dev/pricecharts/price-charts/price-charts:0.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
