apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin-charts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoin-charts
  template:
    metadata:
      labels:
        app: bitcoin-charts
    spec:
      containers:
        - name: bitcoin-charts
          image: us-east5-docker.pkg.dev/bitcoincharts/bitcoincharts/bitcoin_charts:0.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
