apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin_charts-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bitcoin_charts
  template:
    metadata:
      labels:
        app: bitcoin_charts
    spec:
      containers:
        - name: bitcoin_charts
          image: us-east5-docker.pkg.dev/bitcoin_charts/bitcoin_charts/bitcoin_charts:0.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
