apiVersion: v1
kind: Service
metadata:
  name: bitcoin-charts-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: bitcoin-charts
